<Palette FileRevision="18.2.0" Revision="18.2.1" option="0">
    <ItemID idValue="{92434F17-239F-4499-B544-0F21FCA4D0DA}"/>
    <Properties>
        <ItemName>附件阀门-天华给排水</ItemName>
        <Images option="0"/>
        <Time createdUniversalDateTime="2019-03-11T10:51:11" modifiedUniversalDateTime="2019-03-11T10:51:11"/>
    </Properties>
    <Source/>
    <Tools>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{DE5D9389-4817-48FE-9CF1-E78C08D29D18}"/>
            <Properties>
                <ItemName>电接点压力表</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\电接点压力表32.PNG"/>
                    <Image cx="64" cy="64" src="Images\电接点压力表64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>电接点压力表</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{0925110F-34E4-484F-8C59-BF76EC9EA498}"/>
            <Properties>
                <ItemName>压力联动装置</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\压力联动装置32.PNG"/>
                    <Image cx="64" cy="64" src="Images\压力联动装置64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>压力联动装置</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{F112C4AC-46B7-4092-93A0-0D5E81AFE582}"/>
            <Properties>
                <ItemName>压力表</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\压力表32.PNG"/>
                    <Image cx="64" cy="64" src="Images\压力表64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>压力表</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{07F305C9-C9EB-4829-A97D-01E8C86A840E}"/>
            <Properties>
                <ItemName>电子流量计</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\电子流量计32.PNG"/>
                    <Image cx="64" cy="64" src="Images\电子流量计64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>电子流量计</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{C4BF8C97-EDA5-4B92-B9EB-E50A584DB42F}"/>
            <Properties>
                <ItemName>闸阀</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\闸阀32.PNG"/>
                    <Image cx="64" cy="64" src="Images\闸阀64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>闸阀</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{26C862A5-A9CA-4103-869B-52B2B00595F8}"/>
            <Properties>
                <ItemName>薄膜式液位控制阀</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\薄膜式液位控制阀32.PNG"/>
                    <Image cx="64" cy="64" src="Images\薄膜式液位控制阀64.PNG"/>
                </Images>
                <Overlay>
                    <Images option="0">
                        <Image cx="16" cy="16" resource="IDB_DYNAMIC_BLOCK" src="AcTcToolsRes.dll"/>
                    </Images>
                </Overlay>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>1</BlockTypeEx>
                    <BlockName>薄膜式液位控制阀</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                    <ObjectInfo>
                        <Objects>
                            <Object objectId="140689895543072">
                                <AcRxClassInfo className="AcDbDictionary"/>
                                <ObjectData>
                                    <BaseData>
                                        <Dictionary treatElementsAsHard="TRUE">
                                            <Entries>
                                                <Entry keyName="AppDataCache" objectId="140689895545040"/>
                                            </Entries>
                                        </Dictionary>
                                    </BaseData>
                                </ObjectData>
                            </Object>
                            <Object objectId="140689895545040">
                                <AcRxClassInfo className="AcDbDictionary"/>
                                <ObjectData>
                                    <BaseData>
                                        <Dictionary treatElementsAsHard="TRUE">
                                            <Entries>
                                                <Entry keyName="ACAD_ENHANCEDBLOCKDATA" objectId="140689895545056"/>
                                            </Entries>
                                        </Dictionary>
                                    </BaseData>
                                </ObjectData>
                            </Object>
                            <Object objectId="140689895545056">
                                <AcRxClassInfo className="AcDbDictionary"/>
                                <ObjectData>
                                    <BaseData>
                                        <Dictionary treatElementsAsHard="TRUE">
                                            <Entries>
                                                <Entry keyName="21" objectId="140689895545072"/>
                                            </Entries>
                                        </Dictionary>
                                    </BaseData>
                                </ObjectData>
                            </Object>
                            <Object objectId="140689895545072">
                                <AcRxClassInfo className="AcDbXrecord"/>
                                <ObjectData>
                                    <BaseData>
                                        <Xrecord mergeStyle="1"/>
                                        <Resbufs>
                                            <Resbuf restype="1071">
                                                <Long>135625452</Long>
                                            </Resbuf>
                                            <Resbuf restype="1071">
                                                <Long>184556386</Long>
                                            </Resbuf>
                                            <Resbuf restype="70">
                                                <Long>25</Long>
                                            </Resbuf>
                                            <Resbuf restype="70">
                                                <Long>76</Long>
                                            </Resbuf>
                                            <Resbuf restype="10">
                                                <Point>
                                                    <X>1549.559397043993</X>
                                                    <Y>638.9644892203688</Y>
                                                    <Z>0</Z>
                                                </Point>
                                            </Resbuf>
                                            <Resbuf restype="1">
                                                <Text><![CDATA[向右]]>
                                                </Text>
                                            </Resbuf>
                                        </Resbufs>
                                    </BaseData>
                                </ObjectData>
                            </Object>
                        </Objects>
                        <BlockReference>
                            <Object objectId="140689895543040">
                                <AcRxClassInfo className="AcDbBlockReference"/>
                                <ObjectData>
                                    <ExtensionDictionary>
                                        <Dictionary treatElementsAsHard="TRUE">
                                            <Entries>
                                                <Entry keyName="AcDbBlockRepresentation" objectId="140689895543072"/>
                                            </Entries>
                                        </Dictionary>
                                    </ExtensionDictionary>
                                </ObjectData>
                            </Object>
                        </BlockReference>
                    </ObjectInfo>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{1FE87CA0-4AF6-4716-9203-6FA4ACCC8239}"/>
            <Properties>
                <ItemName>消声止回阀</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\消声止回阀32.PNG"/>
                    <Image cx="64" cy="64" src="Images\消声止回阀64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>消声止回阀</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{53320297-94FF-4825-99ED-8E9DC57A1D3C}"/>
            <Properties>
                <ItemName>止回阀</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\止回阀32.PNG"/>
                    <Image cx="64" cy="64" src="Images\止回阀64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>止回阀</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{6C275A64-0DB8-48F8-8865-D1B39AC337F4}"/>
            <Properties>
                <ItemName>温度计</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\温度计32.PNG"/>
                    <Image cx="64" cy="64" src="Images\温度计64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>温度计</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{BB918FE5-E876-4C0E-929D-3D9A7F1F9561}"/>
            <Properties>
                <ItemName>真空表</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\真空表32.PNG"/>
                    <Image cx="64" cy="64" src="Images\真空表64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>真空表</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{5A60F73A-CF9D-470E-9AF9-6AB066EB2BE5}"/>
            <Properties>
                <ItemName>蝶阀</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\蝶阀32.PNG"/>
                    <Image cx="64" cy="64" src="Images\蝶阀64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>蝶阀</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{9F00CBB7-928A-4AD7-BE17-490BE6379A5A}"/>
            <Properties>
                <ItemName>可曲绕橡胶接头</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\可曲绕橡胶接头32.PNG"/>
                    <Image cx="64" cy="64" src="Images\可曲绕橡胶接头64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>可曲绕橡胶接头</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{05B95963-73F7-4944-BD4B-9A3ADF87DA57}"/>
            <Properties>
                <ItemName>遥控信号阀</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\遥控信号阀32.PNG"/>
                    <Image cx="64" cy="64" src="Images\遥控信号阀64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>遥控信号阀</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{70FE90D3-1650-471B-81E7-522016246595}"/>
            <Properties>
                <ItemName>Y型过滤器</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\Y型过滤器32.PNG"/>
                    <Image cx="64" cy="64" src="Images\Y型过滤器64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>Y型过滤器</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>3.141592653589793</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
        <Tool Revision="18.2.1" option="31">
            <ItemID idValue="{8C74D8B2-115A-40EF-8178-7B07131B0906}"/>
            <Properties>
                <ItemName>球阀</ItemName>
                <Images option="0">
                    <Image cx="32" cy="32" src="Images\球阀32.PNG"/>
                    <Image cx="64" cy="64" src="Images\球阀64.PNG"/>
                </Images>
                <Time createdUniversalDateTime="2019-03-06T03:40:55" modifiedUniversalDateTime="2019-03-06T03:40:55"/>
            </Properties>
            <Source/>
            <ToolType>1</ToolType>
            <StockToolRef idValue="{C9AB9290-FC5A-458B-AEB4-BDF9BE6A5E55}"/>
            <Data>
                <GeneralProperties>
                    <Color>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE"/>
                        </BasicPropInfo>
                        <CreateInfo>
                            <AcCmColor mRGB="3221225472"/>
                        </CreateInfo>
                    </Color>
                    <Layer>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="0"/>
                        </BasicPropInfo>
                    </Layer>
                    <Linetype>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Linetype>
                    <LinetypeScale>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="3" value="1"/>
                        </BasicPropInfo>
                    </LinetypeScale>
                    <PlotStyle>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </PlotStyle>
                    <LineWeight>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="2" value="-1"/>
                        </BasicPropInfo>
                    </LineWeight>
                    <Transparency>
                        <BasicPropInfo>
                            <PropValue unspecified="FALSE" valueType="1" value="ByLayer"/>
                        </BasicPropInfo>
                    </Transparency>
                    <Textstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Textstyle>
                    <Dimstyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Dimstyle>
                    <Tablestyle>
                        <BasicPropInfo>
                            <PropValue unspecified="TRUE" valueType="1"/>
                        </BasicPropInfo>
                    </Tablestyle>
                </GeneralProperties>
                <Block>
                    <BlockType>1</BlockType>
                    <BlockTypeEx>0</BlockTypeEx>
                    <BlockName>球阀</BlockName>
                    <SourceFile>给排水模块.dwg</SourceFile>
                    <InsertAs>1</InsertAs>
                    <XrefType>0</XrefType>
                    <Scale>1</Scale>
                    <AuxiliaryScale>NONE</AuxiliaryScale>
                    <Rotation>0</Rotation>
                    <PromptRotation>0</PromptRotation>
                    <Explode>0</Explode>
                </Block>
            </Data>
        </Tool>
    </Tools>
</Palette>
